sites:
  encuentra24:
    domain: https://www.encuentra24.com
    url: https://www.encuentra24.com/panama-en/real-estate-for-sale-apartments-condos
    queries:
      listing_links: '//a[@class="ann-box-title"]/@href'
      listing_title:
        [
          '//div[contains(@class, "image__text")]/h1[contains(@class, "__title")]/text()',
          '//div[@class="col-800"]/b/text()',
        ]
      listing_price:
        [
          '//div[contains(@class, "--price")]/text()[last()]',
          '//div[@class="offer-price"]/text()[1]',
        ]
      listing_description:
        [
          '//div[contains(@class, "about__text")]/text()',
          '//div[@class="col-800"]/p/text()',
        ]
      next_page: '//li[@class="arrow"]/a[@rel="next"]/./@href'
  mitula:
    domain: https://casas.mitula.com.pa
    url: https://casas.mitula.com.pa/searchRE/orden-0/op-1/q-apartamentos-panama?req_sgmt=REVTS1RPUDtTRU87U0VSUDs=
    queries:
      listing_links: '//div[@class="item-card__description"]/a/@href'
      listing_title: '//div[@class="title-detail"]/text()'
      listing_price: '//div[@class="adPrice"]/text()'
      listing_description: '//div[@class="description-detail"]/text()'
      next_page: '//li[contains(@class,"activated")]/following-sibling::li/a/@href'
